### ISSUE TITLE
feat: post-render patches

### ISSUE THREAD

**Issue by oliverbaehler** [projectsveltos/addon-controller#595]
**Is your feature request related to a problem? Please describe.**
One feature i have used the most in combination with FluxCD is the option to change values of a helm chart via Kustomize-Patches, see the following:

* https://fluxcd.io/flux/components/helm/helmreleases/#post-renderers

I was wondering how much interest is there to implement this.

**Describe the solution you'd like**

Add for Helm-Charts (or maybe scoped to the entire Profile?) The option to enter kustomize patches. We should probably add the functionality that we can use sprig templating within the patches definition, because in most use-cases you probably want to patch cluster-specific stuff on charts.

**Comment by gianlucam76** [comment]
Thank you for proposing this @oliverbaehler.  This would be a lovely addition. 

I see Helm SDK supports this, so all that is needed is to extend ClusterProfile/Profile helm section and then set `installClient.PostRenderer` and `upgradeClient.PostRenderer` 

```
type PostRenderer interface {
    // Run expects a single buffer filled with Helm rendered manifests. It
    // expects the modified results to be returned on a separate buffer or an
    // error if there was an issue or failure while running the post render step
    Run(renderedManifests *bytes.Buffer) (modifiedManifests *bytes.Buffer, err error)
}
```

Do you want to look into this? Otherwise I won't mind taking care of it. Thank you!

**Comment by gianlucam76** [comment]
Closing as taken care by [this](https://github.com/projectsveltos/addon-controller/commit/8f44faa553426b7e06252c133dca375012b13ad8)
